"""Generate 150 daily plan markdown files from curriculum data.

Run: python scripts/generate_daily_plans.py
Output: daily-plans/day-001.md ... day-150.md
"""
from pathlib import Path

OUT = Path(__file__).parent.parent / "daily-plans"
OUT.mkdir(exist_ok=True)

# Format: (day_num, day_of_week, phase, project, hours, tasks, resources, deliverable, cadences)
# tasks: list of strings
# resources: list of strings (or empty)
# deliverable: string or None
# cadences: list of strings (or empty)

DAYS = [
    # === PHASE 1: Foundations + User Research (Days 1-12) ===
    (1, "Mon", 1, "Setup", 2,
     ["Install Homebrew, Python 3.12, uv, Git, Cursor (30 min)",
      "Setup GitHub SSH keys + professional handle",
      "Create GitHub repo `ai-engineer-journey` (or push existing tracker)",
      "Top up $30 OpenAI + $30 Anthropic credits",
      "**First chat completion working** (OpenAI + Anthropic)",
      "Save `.cursorrules` template (see IMPROVEMENTS.md)"],
     ["realpython.com/installing-python", "platform.openai.com/docs/quickstart",
      "docs.anthropic.com/quickstart", "astral.sh/uv"],
     "Repo live + first LLM API calls working + LinkedIn post #1",
     ["LinkedIn post #1 — 'Day 1 of AI Engineer transition'"]),

    (2, "Tue", 1, "Setup", 2,
     ["Python idioms (2 hrs): list/dict comprehensions, f-strings, type hints, async/await, virtual envs",
      "Skip 'what is a variable' — you know",
      "Practice: rewrite 1 small .NET utility in Python"],
     ["realpython.com (skim, don't deep-read)", "docs.python.org/3/tutorial"],
     None, []),

    (3, "Wed", 1, "Setup", 2,
     ["Pydantic v2: BaseModel, validators, computed fields",
      "FastAPI: endpoints w/ Pydantic request/response",
      "Build: TODO API w/ 4 endpoints (CRUD)"],
     ["docs.pydantic.dev", "fastapi.tiangolo.com/tutorial (skim first 5 sections)"],
     "Working FastAPI TODO API", []),

    (4, "Thu", 1, "Setup", 2,
     ["Install Instructor library",
      "LLM → Pydantic objects in 5 lines",
      "Build: extract person info from email → Person model"],
     ["jxnl.github.io/instructor"],
     None, []),

    (5, "Sat", 1, "Email Classifier", 5,
     ["Repo: `fintech-email-classifier`",
      "Build: email → JSON {category, urgency, sentiment, action_items, summary}",
      "Streamlit UI in 1 hr",
      "Deploy to Streamlit Cloud",
      "Demo GIF in README (kap.app)"],
     ["docs.streamlit.io", "share.streamlit.io"],
     "Live email classifier demo URL",
     ["LinkedIn post #2 — 'First AI project shipped'"]),

    (6, "Sun", 1, "Setup", 2,
     ["**Sunday block:**",
      "1 hr: Identify 20 fintech analysts/PMs on LinkedIn — save to Airtable",
      "30 min: Damodaran 'What is Valuation?' intro (YouTube)",
      "30 min: Plan Week 2"],
     ["youtube.com/@AswathDamodaranonValuation"],
     "20 analyst profiles saved for Day 7 outreach",
     ["Sunday block routine"]),

    (7, "Mon", 1, "User Research", 2,
     ["Send 20 personalized LinkedIn DMs to fintech analysts/PMs",
      "Template: 'I'm a software engineer building AI tools for finance. Could I ask 3 questions about your workflow? 15-min call?'",
      "Goal: 5 yes responses"],
     ["LinkedIn Sales Nav free trial (helpful)"],
     "20 outreach messages sent", []),

    (8, "Tue", 1, "User Research", 2,
     ["Analyst interview #1 (15 min)",
      "Analyst interview #2 (15 min)",
      "Questions: workflow, biggest pain, what would 10x output, AI tool buying process",
      "Note insights in Notion + tracker/interviews/analysts/",
      "LinkedIn post: 'Talked to 2 fintech analysts today. Here's what surprised me...'"],
     ["tracker/interviews/analysts/README.md (question bank)"],
     "2 interview notes saved",
     ["LinkedIn post #3"]),

    (9, "Wed", 1, "Email Classifier", 2,
     ["30 hand-labeled emails for accuracy testing",
      "Pytest-style evals script",
      "README polish — architecture, lessons, live link"],
     [],
     "Eval suite + polished README", []),

    (10, "Thu", 1, "User Research", 2,
     ["Analyst interview #3 (15 min)",
      "Analyst interview #4 (15 min)",
      "Synthesize patterns across all 4 calls",
      "Identify which Project (1, 2, 3, 4) addresses biggest pain"],
     [],
     "4 interviews done, pattern synthesis", []),

    (11, "Sat", 1, "User Research + Blog", 5,
     ["Final analyst interview #5 (15 min)",
      "Write blog post #1: 'I Talked to 5 Fintech Analysts About AI. Here's What They Want.'",
      "Publish on Medium + LinkedIn + Dev.to",
      "**HUGE distribution play** — analysts will share"],
     ["medium.com (sign up if needed)", "dev.to"],
     "Blog post #1 published on 3 platforms",
     ["Blog post #1 LIVE", "LinkedIn carousel post"]),

    (12, "Sun", 1, "Retrospective", 2,
     ["**Sunday block + Phase 1 retro:**",
      "1 hr: Phase 1 retrospective in Notion — what worked, what didn't",
      "30 min: Damodaran video #2",
      "30 min: Plan Phase 2 — adjust Project 1 scope based on user feedback",
      "**Phase 1 complete:** Email classifier shipped, 5 user interviews done, blog post live"],
     [],
     "Phase 1 retro doc + Phase 2 plan adjusted",
     ["Sunday block routine"]),

    # === PHASE 2: RAG + Project 1 SEC 10-K Analyzer (Days 13-37) ===
    (13, "Mon", 2, "Project 1: SEC 10-K Analyzer", 2,
     ["Embeddings concepts",
      "DeepLearning.AI: 'Vector Databases: Embeddings to Applications' (free, 1 hr)",
      "text-embedding-3-small basics",
      "Cosine similarity intuition"],
     ["deeplearning.ai/short-courses"],
     None, []),

    (14, "Tue", 2, "Project 1: SEC 10-K Analyzer", 2,
     ["ChromaDB local install",
      "Pinecone signup, create index (verify free tier)",
      "Build: semantic search over 100 sentences"],
     ["docs.trychroma.com", "docs.pinecone.io"],
     "Both Chroma + Pinecone working", []),

    (15, "Wed", 2, "Project 1: SEC 10-K Analyzer", 2,
     ["sec.gov/edgar tour",
      "Download AAPL, MSFT, JPM 10-Ks",
      "pypdf, pdfplumber comparison",
      "Read 1 10-K Risk Factors section fully"],
     ["sec.gov/edgar"],
     None, []),

    (16, "Thu", 2, "Project 1: SEC 10-K Analyzer", 2,
     ["DeepLearning.AI: 'LangChain for LLM App Development' (skim, you know basics now)",
      "LCEL, document loaders, text splitters",
      "Build: tiny RAG over 1 PDF"],
     ["python.langchain.com/docs"],
     None, []),

    (17, "Sat", 2, "Project 1: SEC 10-K Analyzer", 5,
     ["Repo: `sec-10k-analyzer`",
      "FastAPI + Streamlit skeleton",
      "sec-edgar-downloader integration",
      "PDF → chunk → embed → Pinecone (metadata: company, date, section)",
      "Test: ingest AAPL 10-K end-to-end"],
     ["pypi.org/project/sec-edgar-downloader"],
     "AAPL 10-K ingested into Pinecone", []),

    (18, "Sun", 2, "Sunday Block", 2,
     ["1 hr: Outline blog post #2 — 'Building Production RAG'",
      "30 min: Money Stuff newsletter (subscribe + read 2)",
      "30 min: Week 4 plan",
      "**Build-in-public:** LinkedIn post #4 — 'Building SEC 10-K analyzer' + diagram"],
     ["bloomberg.com/account/newsletters/money-stuff"],
     None, ["LinkedIn post #4 — architecture diagram"]),

    (19, "Mon", 2, "Project 1: SEC 10-K Analyzer", 2,
     ["FastAPI POST /query — ticker + question",
      "Top-K retrieve → Claude → answer + sources",
      "Test: 'What are AAPL's risk factors?'"],
     [],
     "Working Q&A endpoint", []),

    (20, "Tue", 2, "Project 1: SEC 10-K Analyzer", 2,
     ["Streamlit: ticker dropdown, question input, answer",
      "Citations w/ chunk previews",
      "Loading states"],
     [],
     "Streamlit UI working", []),

    (21, "Wed", 2, "Project 1: SEC 10-K Analyzer", 2,
     ["Filter by section (Risk Factors, MD&A, etc.)",
      "Section-aware retrieval",
      "**START 3 LinkedIn posts/week cadence**"],
     [],
     None, ["LinkedIn post #5 — RAG architecture (3x/wk cadence STARTS)"]),

    (22, "Thu", 2, "Project 1: SEC 10-K Analyzer", 2,
     ["Compare 2 companies' 10-Ks",
      "Ingest 3 years of 1 company → YoY queries"],
     [],
     "Multi-doc + YoY comparison working", []),

    (23, "Sat", 2, "Project 1: SEC 10-K Analyzer", 5,
     ["Redis cache (Upstash free)",
      "Cost dashboard",
      "Test 3 chunking strategies, pick best",
      "LinkedIn post #6 — chunking experiments results"],
     ["upstash.com (Redis free)"],
     "Caching + chunking experiments documented",
     ["LinkedIn post #6"]),

    (24, "Sun", 2, "Sunday Block", 2,
     ["1 hr: Continue blog post #2",
      "30 min: Damodaran finance lecture",
      "30 min: Plan Week 5"],
     [], None, ["Sunday block routine"]),

    (25, "Mon", 2, "Project 1: SEC 10-K Analyzer", 2,
     ["20 hand-graded Q&A pairs across 3 companies",
      "Pytest-style evals, scoring over time"],
     [],
     "Eval suite live", []),

    (26, "Tue", 2, "Project 1: SEC 10-K Analyzer", 2,
     ["Add LangSmith tracing to ingestion + query",
      "Inspect failures"],
     ["smith.langchain.com"],
     "LangSmith tracing live", []),

    (27, "Wed", 2, "Project 1: SEC 10-K Analyzer", 2,
     ["Backend: Render Docker",
      "Frontend: Streamlit Cloud",
      "Pinecone prod index",
      "Custom domain"],
     [],
     "Project 1 LIVE on production",
     ["LinkedIn post #7 — live demo announcement"]),

    (28, "Thu", 2, "Project 1: SEC 10-K Analyzer", 2,
     ["Architecture diagram (excalidraw)",
      "30-sec demo GIF",
      "Lessons learned section in README"],
     ["excalidraw.com"],
     "README polished", []),

    (29, "Sat", 2, "User Feedback Round 2", 5,
     ["Send Project 1 demo link to 5 interviewees from Days 8-11",
      "Schedule 5-min check-ins for next week",
      "Collect feedback, fix top 3 issues live"],
     [],
     "5 follow-up sessions scheduled", []),

    (30, "Sun", 2, "Sunday Block + LeetCode Start", 2,
     ["1 hr: Finalize blog post #2",
      "30 min: 10-K reading",
      "30 min: 1 LeetCode medium problem (CADENCE STARTS — 1/wk)",
      "**CADENCE LIVE:** 3 LinkedIn/wk + 1 LeetCode/wk"],
     ["neetcode.io"],
     None, ["LeetCode 1/wk STARTS", "Sunday block routine"]),

    (31, "Mon", 2, "Project 1: Launch", 2,
     ["Submit blog #2 to Towards Data Science (Medium)",
      "Cross-post Dev.to, LinkedIn, X",
      "Show HN submission"],
     ["medium.com/towards-data-science"],
     "Blog #2 published, Show HN posted",
     ["LinkedIn post #8 — blog launch"]),

    (32, "Tue", 2, "Project 1: Iteration", 2,
     ["Incorporate top 3 fixes from analyst feedback",
      "Push v1.1",
      "Re-share with analysts"],
     [],
     "v1.1 deployed", []),

    (33, "Wed", 2, "Project 5: Spec", 2,
     ["Spec doc: features, monetization, growth plan",
      "Pricing: free weekly, ₹199/mo daily + alerts",
      "**Treat as STARTUP not side project**"],
     [],
     "Project 5 spec doc ready",
     ["LinkedIn post #9 — Project 5 teaser"]),

    (34, "Thu", 2, "Project 5: Data Sources", 2,
     ["BSE/NSE corporate filings (RSS/API)",
      "moneycontrol.com (scrape carefully, robots.txt)",
      "screener.in API research",
      "Pick 3 reliable sources"],
     ["bseindia.com", "nseindia.com"],
     "Data sources picked", []),

    (35, "Sat", 2, "Project 5: Architecture + VPS", 5,
     ["Repo: `nifty-earnings-digest`",
      "VPS setup: Python 3.12, Docker, nginx",
      "Configure subdomain on owned domain",
      "Architecture: VPS cron → fetch → analyze → email + DB"],
     [],
     "VPS configured for Project 5", []),

    (36, "Sun", 2, "Sunday Block", 2,
     ["1 hr: Project 5 landing page copy draft",
      "30 min: India fintech landscape (Razorpay engineering blog)",
      "30 min: Week 7 plan"],
     ["razorpay.com/blog/engineering"],
     None, ["Sunday block routine"]),

    (37, "Mon", 2, "Phase 2 Wrap", 2,
     ["Notion retrospective for Phase 2",
      "LinkedIn carousel post — Project 1 deep dive"],
     [],
     "Phase 2 retro + LinkedIn carousel",
     ["LinkedIn post #10 — Project 1 carousel deep dive"]),

    # === PHASE 3: Project 5 Launch + Project 2 (Days 38-67) ===
    (38, "Tue", 3, "Project 5: Data Pipeline", 2,
     ["BSE/NSE filing fetcher",
      "Earnings transcript scraper",
      "Store in PostgreSQL on VPS"],
     [], "Data pipeline running", []),

    (39, "Wed", 3, "Project 5: LLM Summary", 2,
     ["Per-filing: summary + sentiment + key takeaways",
      "Use Claude Haiku (cheap)",
      "Store outputs in DB"],
     [], "LLM analysis pipeline working", []),

    (40, "Thu", 3, "Project 5: Email", 2,
     ["Resend.com free tier (verify limits)",
      "Responsive HTML email template",
      "Test send to 3 friend emails"],
     ["resend.com"], "Test emails delivered",
     ["LinkedIn post #11"]),

    (41, "Sat", 3, "Project 5: Landing Page", 5,
     ["Next.js + Tailwind",
      "Hero, value prop, signup form",
      "Vercel deploy w/ owned domain",
      "PostHog analytics"],
     ["nextjs.org/learn", "vercel.com", "posthog.com"],
     "Landing page LIVE", []),

    (42, "Sun", 3, "Sunday Block", 2,
     ["1 hr: Project 5 launch tweet + LinkedIn copy",
      "30 min: Indian fintech reading",
      "30 min: Week 8 plan"],
     [], None,
     ["LinkedIn post #12 — 'Building fintech newsletter SaaS'",
      "Sunday block routine"]),

    (43, "Mon", 3, "Project 5: Cron", 2,
     ["systemd timer on VPS",
      "Weekly trigger first",
      "Failure alerts to email"],
     [], "Automated weekly cron working", []),

    (44, "Tue", 3, "Project 5: First Newsletter", 2,
     ["Manual trigger to 10 testers",
      "Iterate on quality",
      "Get feedback"],
     [], "First newsletter sent to 10 users", []),

    (45, "Wed", 3, "Project 5: PUBLIC LAUNCH", 2,
     ["Reddit: r/IndianStockMarket, r/IndiaInvestments",
      "LinkedIn announcement",
      "X thread",
      "Indie Hackers post",
      "Goal: 50 signups Week 1"],
     ["indiehackers.com"], "PROJECT 5 LIVE TO PUBLIC",
     ["LinkedIn post #13 — Project 5 LAUNCH",
      "X thread launch",
      "Reddit launch posts"]),

    (46, "Thu", 3, "Project 5: Monitor + Project 2 Spec", 2,
     ["Monitor Project 5 signups",
      "Fix bugs from real users",
      "Write Project 2 spec doc — `invoice-ap-auditor`"],
     [], "Project 2 spec ready", []),

    (47, "Sat", 3, "Project 2: Extraction", 5,
     ["Repo: `invoice-ap-auditor`",
      "PyMuPDF, pdfplumber comparison",
      "Multimodal extraction (Claude vision API)",
      "Pydantic Invoice schema (nested w/ line items)",
      "Test on 30 sample invoices"],
     ["github.com/pymupdf/PyMuPDF"],
     "Invoice extraction pipeline working", []),

    (48, "Sun", 3, "Sunday Block", 2,
     ["1 hr: Blog post #3 outline — 'Shipping Newsletter SaaS in 2 Weeks'",
      "30 min: Money Stuff",
      "30 min: Plan Week 9"],
     [], None,
     ["LinkedIn post #14 — Project 5 launch results",
      "Sunday block routine"]),

    (49, "Mon", 3, "Project 2: DB", 2,
     ["Supabase OR VPS Postgres",
      "SQLAlchemy ORM, Alembic migrations",
      "Tables: invoices, line_items, vendors, audit_flags"],
     ["supabase.com", "docs.sqlalchemy.org"],
     "Project 2 DB schema deployed", []),

    (50, "Tue", 3, "Project 2: Audit Rules + Daily X", 2,
     ["Rule: duplicate, math error, tax mismatch, missing fields",
      "Each rule = function returning AuditFlag",
      "**Daily X cadence starts (3x/wk per IMPROVEMENTS.md)**"],
     [],
     "Audit rules engine v1",
     ["X 3x/wk cadence STARTS (was daily, cut per IMPROVEMENTS)"]),

    (51, "Wed", 3, "Project 5: Iteration", 2,
     ["Address top 3 user complaints",
      "Add unsubscribe handling",
      "Improve email quality"],
     [], "Project 5 v1.1", []),

    (52, "Thu", 3, "Project 2: LLM Audit", 2,
     ["Beyond rules: 'Does this look suspicious?'",
      "Hybrid: rules + LLM second opinion"],
     [], "LLM-powered audit working", []),

    (53, "Sat", 3, "Project 2: Frontend", 5,
     ["Next.js 14 App Router",
      "Upload, list, detail views",
      "Connect to FastAPI"],
     ["nextjs.org/docs"], "Frontend skeleton working", []),

    (54, "Sun", 3, "Sunday Block + Blog #3", 2,
     ["1 hr: Blog post #3 publish — Project 5 launch story",
      "30 min: 10-K reading (start India: RELIANCE annual)",
      "30 min: Plan Week 10"],
     [], "Blog #3 LIVE",
     ["Blog #3 published",
      "LinkedIn post #15 — blog #3 announcement",
      "Sunday block routine"]),

    (55, "Mon", 3, "Project 2: Bulk Upload", 2,
     ["Drag-drop, progress bar",
      "FastAPI BackgroundTasks"],
     [], None,
     ["LinkedIn post #16 — Project 2 progress"]),

    (56, "Tue", 3, "Project 2: Error Handling", 2,
     ["Tenacity for LLM retries",
      "Exponential backoff",
      "Graceful degradation (rules-only if LLM fails)"],
     ["tenacity.readthedocs.io"], None, []),

    (57, "Wed", 3, "Project 5: Push to 100 Signups", 2,
     ["Twitter Spaces about Indian markets (or join one)",
      "DM 20 finance influencers",
      "Consider Product Hunt timing"],
     ["producthunt.com"],
     "Project 5 at 100+ signups (target)", []),

    (58, "Thu", 3, "Project 2: Cost Optimization", 2,
     ["Claude Haiku for extraction, Sonnet for ambiguous",
      "Track cost per invoice",
      "**Anthropic prompt caching from today** (saves $$)"],
     ["docs.anthropic.com/en/docs/build-with-claude/prompt-caching"],
     "Costs optimized", []),

    (59, "Sat", 3, "Project 2: Dashboard + Tracing", 5,
     ["Stats: invoices processed, flags, $ savings",
      "LangSmith tracing",
      "Vendor leaderboard"],
     [], "Admin dashboard live", []),

    (60, "Sun", 3, "User Research Round 2", 2,
     ["**Sunday block + 5 user interviews:**",
      "1 hr: Reach 5 newsletter users + 5 Project 1 users",
      "30 min: Stratechery free post",
      "30 min: Plan Week 11"],
     ["stratechery.com/free-tier"],
     "10 user feedback calls scheduled",
     ["Sunday block routine"]),

    (61, "Mon", 3, "Project 2: Eval Suite", 2,
     ["50 invoices w/ ground truth",
      "Field-level extraction accuracy",
      "Flag precision/recall"],
     [], "Eval suite live", []),

    (62, "Tue", 3, "Project 2: Deploy", 2,
     ["Backend: Render Docker",
      "Frontend: Vercel",
      "DB: Supabase",
      "Live + tested"],
     [], "Project 2 LIVE", []),

    (63, "Wed", 3, "User Feedback Calls", 2,
     ["5 calls today: Project 5 + Project 1 users",
      "Synthesize insights"],
     [],
     "User feedback synthesized",
     ["LinkedIn post #17 — '10 user calls taught me...'"]),

    (64, "Thu", 3, "Project 2: Demo + Polish", 2,
     ["Loom 2-min walkthrough",
      "Architecture diagram",
      "README polish"],
     ["loom.com"], "Demo video + polished README",
     ["LinkedIn post #18 — Project 2 launch teaser"]),

    (65, "Sat", 3, "Project 2: LAUNCH + Blog #4", 5,
     ["Publish blog #4 — 'I Built an AI Invoice Auditor'",
      "Medium + Dev.to + LinkedIn",
      "Show HN submission"],
     [], "Blog #4 LIVE + Project 2 launched",
     ["Blog #4 published"]),

    (66, "Sun", 3, "Sunday Block", 2,
     ["1 hr: Phase 3 retrospective",
      "30 min: India fintech reading",
      "30 min: Plan Phase 4"],
     [], None, ["Sunday block routine"]),

    (67, "Mon", 3, "Phase 3 Wrap", 2,
     ["2 projects shipped (Project 1 + 2)",
      "Project 5 at 100+ signups (target)",
      "4 blog posts live"],
     [], "Phase 3 milestone reached",
     ["LinkedIn post #19 — phase milestone celebration"]),

    # === PHASE 4: Agents + Project 3 (Days 68-92) ===
    (68, "Tue", 4, "Project 3: Function Calling", 2,
     ["OpenAI + Anthropic tool use",
      "Parallel tool calls",
      "Tool choice strategies"],
     [], None, []),

    (69, "Wed", 4, "Project 3: Simple Tools", 2,
     ["Tool 1: fetch_stock_price (yfinance)",
      "Tool 2: fetch_news (NewsAPI free tier)",
      "Tool 3: calculator (LangChain built-in)"],
     ["pypi.org/project/yfinance", "newsapi.org"],
     "3 tools working", []),

    (70, "Thu", 4, "Project 3: ReAct Pattern", 2,
     ["Reasoning + Acting loop manual implementation (no framework)",
      "Understand internals"],
     [], None,
     ["LinkedIn post #20 — agents explainer"]),

    (71, "Sat", 4, "Project 3: LangGraph", 5,
     ["DeepLearning.AI: 'AI Agents in LangGraph' (1.5 hrs)",
      "Nodes, edges, state",
      "Build: 3-tool agent in LangGraph"],
     ["langchain-ai.github.io/langgraph"],
     "LangGraph 3-tool agent working", []),

    (72, "Sun", 4, "Sunday Block", 2,
     ["1 hr: Blog post #5 outline — 'LLM Agents That Don't Suck'",
      "30 min: Damodaran",
      "30 min: Plan Week 13"],
     [], None, ["Sunday block routine"]),

    (73, "Mon", 4, "Project 3: Setup + SEC Tool", 2,
     ["Repo: `equity-research-agent`",
      "LangGraph state machine",
      "SEC EDGAR tool (reuse from Project 1)"],
     [], "Project 3 skeleton + SEC tool", []),

    (74, "Tue", 4, "Project 3: News + Transcripts", 2,
     ["NewsAPI integration",
      "Financial Modeling Prep API for transcripts"],
     ["financialmodelingprep.com"],
     "News + transcript tools", []),

    (75, "Wed", 4, "Project 3: Peer + Ratios", 2,
     ["yfinance + SIC codes",
      "Functions: P/E, P/B, ROE, gross margin, FCF yield"],
     [],
     "Peer lookup + ratios tools",
     ["LinkedIn post #21 — agent tools demo"]),

    (76, "Thu", 4, "Project 3: Multi-agent Patterns", 2,
     ["Supervisor pattern",
      "Sequential agents",
      "Resource: langchain-ai.github.io/langgraph/tutorials"],
     ["langchain-ai.github.io/langgraph/tutorials/multi_agent"],
     None, []),

    (77, "Sat", 4, "Project 3: Workflow", 5,
     ["LangGraph nodes: plan → fetch → analyze → write",
      "State: question, gathered_data, analysis, report",
      "Test: 'Is NVIDIA overvalued?'"],
     [], "Research workflow working end-to-end", []),

    (78, "Sun", 4, "Sunday Block", 2,
     ["1 hr: Continue blog #5",
      "30 min: Levine",
      "30 min: Plan Week 14"],
     [], None, ["Sunday block routine"]),

    (79, "Mon", 4, "Project 5: Razorpay Prep", 2,
     ["Razorpay test mode setup",
      "Premium feature design: daily emails + alerts + custom watchlists",
      "Don't ship paid yet — prep only"],
     ["razorpay.com/docs"], "Razorpay test mode working", []),

    (80, "Tue", 4, "Project 3: Output + FIRST MOCK INTERVIEW", 2,
     ["Markdown report template",
      "Sections: Summary, Financials, Risks, Peers, Verdict",
      "**FIRST MOCK INTERVIEW** (Pramp/interviewing.io 1 hr)"],
     ["pramp.com", "interviewing.io"],
     "Report template + mock done",
     ["FIRST MOCK INTERVIEW"]),

    (81, "Wed", 4, "Project 3: PDF Export", 2,
     ["markdown → PDF (weasyprint)",
      "Polished look"],
     ["weasyprint.org"], "PDF export working", []),

    (82, "Thu", 4, "Project 3: Streamlit UI", 2,
     ["Stream agent steps (show thinking)",
      "Final report preview + download"],
     [], "Streaming UI working", []),

    (83, "Sat", 4, "Project 3: Eval + Deploy", 5,
     ["10 research questions w/ gold answers",
      "Measure factual accuracy, completeness",
      "Deploy to HF Space"],
     ["huggingface.co/spaces"],
     "Project 3 LIVE",
     ["LinkedIn post #22 — Project 3 launch teaser"]),

    (84, "Sun", 4, "Sunday Block", 2,
     ["1 hr: Blog #5 polish",
      "30 min: India fintech reading (RBI annual)",
      "30 min: Plan Week 15",
      "**Project 5 check:** Should be at 200+ signups"],
     ["rbi.org.in"], None, ["Sunday block routine"]),

    (85, "Mon", 4, "Project 3: LAUNCH + Blog #5", 2,
     ["Medium publish (Towards Data Science)",
      "Show HN",
      "LinkedIn carousel",
      "X thread"],
     [], "Blog #5 LIVE",
     ["Blog #5 published",
      "LinkedIn carousel #23"]),

    (86, "Tue", 4, "Project 5: Razorpay LIVE", 2,
     ["Premium tier launches",
      "Email existing users with offer",
      "Goal: 5 paid in week 1"],
     [], "PROJECT 5 MONETIZING",
     ["LinkedIn post #24 — paid tier launch"]),

    (87, "Wed", 4, "YC App Research", 2,
     ["Read YC's 'How to Apply' guide",
      "Watch YC partner videos",
      "Outline Project 5 as YC application"],
     ["ycombinator.com/apply"], "YC application outlined", []),

    (88, "Thu", 4, "First Paid Customer", 2,
     ["**LinkedIn post #25 — 'Got my first paying customer'**",
      "This is RESUME GOLD"],
     [],
     "First paying customer (target)",
     ["LinkedIn post #25 — first paid customer celebration"]),

    (89, "Sat", 4, "User Research Round 3", 5,
     ["5 calls w/ paid customers (if any) + 5 free users",
      "Identify what made them pay (or not)",
      "Adjust pricing/features"],
     [], "10 calls done, pricing iterated", []),

    (90, "Sun", 4, "Sunday Block + YC App Draft", 2,
     ["1 hr: YC application draft (Question 1: What does company do?)",
      "30 min: Damodaran valuation deep dive",
      "30 min: Plan Week 16"],
     [], "YC app Q1 drafted", ["Sunday block routine"]),

    (91, "Mon", 4, "YC App Q2-5", 2,
     ["Why this team? Why now? What are you building?",
      "Draft, refine"],
     [], "YC app Q2-5 drafted", []),

    (92, "Tue", 4, "YC App Metrics", 2,
     ["Document Project 5 numbers: signups, MRR, growth rate"],
     [],
     "YC app metrics section ready",
     ["LinkedIn post #26 — Phase 4 milestone (3 projects + 1 startup)"]),

    # === PHASE 5: India Specialization + Project 4 + YC Submit (Days 93-117) ===
    (93, "Wed", 5, "Project 4: Spec", 2,
     ["Spec: Indian Tax Document Analyzer",
      "Reuse extraction code from P2",
      "Repo: `india-tax-analyzer`"],
     [], "Project 4 spec ready", []),

    (94, "Thu", 5, "Project 4: Tax Research", 2,
     ["Old vs new regime FY 2024-25",
      "Deductions: 80C, 80D, HRA, LTA",
      "ClearTax guides"],
     ["cleartax.in/guides"], "India tax rules understood", []),

    (95, "Sat", 5, "Project 4: Extraction + Calculator + YC DECISION", 5,
     ["Pydantic schemas: SalarySlip, Form16, ITR",
      "Old + new regime calculator",
      "Test w/ sample Form 16",
      "**YC DECISION TREE** (per IMPROVEMENTS.md):",
      "  IF Project 5 ≥ 100 users OR ≥ $100 MRR → apply YC",
      "  ELSE → skip, focus job hunt"],
     [], "Calculator working + YC decision made", []),

    (96, "Sun", 5, "Sunday Block", 2,
     ["1 hr: YC app polish (if applying)",
      "30 min: NPCI/UPI architecture",
      "30 min: Plan Week 17"],
     ["npci.org.in"], None, ["Sunday block routine"]),

    (97, "Mon", 5, "Project 4: LLM Tax Q&A", 2,
     ["RAG over Income Tax Act sections",
      "Citations to sections"],
     [], "RAG tax Q&A working", []),

    (98, "Tue", 5, "Project 4: Streamlit UI", 2,
     ["Upload Form 16 → summary",
      "Regime comparison",
      "Q&A chat"],
     [], "Project 4 UI working", []),

    (99, "Wed", 5, "Project 4: Privacy", 2,
     ["Documents NOT stored",
      "Privacy policy",
      "Rate limiting"],
     [], "Privacy + security in place", []),

    (100, "Thu", 5, "🎯 YC W26 SUBMIT (or skip)", 2,
     ["IF traction met → final review of YC app, SUBMIT",
      "ELSE → use this time for portfolio polish",
      "**MILESTONE: 100 days**"],
     [],
     "YC submitted OR portfolio polish done",
     ["LinkedIn post #27 — YC submission OR 100-day milestone"]),

    (101, "Sat", 5, "Project 4: Eval + Deploy", 5,
     ["10 sample Form 16s w/ known correct calculations",
      "HF Spaces deploy",
      "Demo GIF + README"],
     [], "Project 4 LIVE", []),

    (102, "Sun", 5, "Sunday Block", 2,
     ["1 hr: Blog post outline — final wrap-up post",
      "30 min: India fintech reading",
      "30 min: Plan Week 18"],
     [], None, ["Sunday block routine"]),

    (103, "Mon", 5, "Project 4: Launch (LinkedIn only)", 2,
     ["LinkedIn post about Project 4 (NOT full blog post — cut per IMPROVEMENTS)",
      "Tag #IndianStartups #FinTechIndia",
      "Demo GIF + LinkedIn carousel"],
     [],
     "Project 4 LinkedIn launch",
     ["LinkedIn carousel #28 — Project 4 launch (no full blog)"]),

    (104, "Tue", 5, "Ragas Evals on Project 1", 2,
     ["Add Ragas to Project 1",
      "Faithfulness, answer relevancy, context precision",
      "Track metrics over time"],
     ["docs.ragas.io"], "Ragas evals live on P1", []),

    (105, "Wed", 5, "Anthropic Prompt Caching All Projects", 2,
     ["Add prompt caching to P1, P2, P3",
      "Document savings",
      "Was already started Day 58 — extend to all"],
     [], "Caching across all projects", []),

    (106, "Thu", 5, "GitHub Actions CI for Evals", 2,
     ["Run evals on every PR",
      "Block merges on regression"],
     ["docs.github.com/actions"], "CI evals enforcing quality", []),

    (107, "Sat", 5, "Cost Blog #6 Draft", 5,
     ["Document cost-cutting across all projects",
      "Blog post draft — 'How I Cut LLM Costs 80%'"],
     [], "Blog #6 drafted", []),

    (108, "Sun", 5, "Sunday Block + Blog #6 Finalize", 2,
     ["1 hr: Blog #6 finalize",
      "30 min: 10-K reading",
      "30 min: Plan Week 19"],
     [], None,
     ["Sunday block routine",
      "Blog #6 ready to publish"]),

    (109, "Mon", 5, "Project 5: Push to 500 Users", 2,
     ["Reddit AMAs in Indian investing subs",
      "Twitter/X live spaces",
      "Influencer outreach (5 finance creators)"],
     [], "Project 5 at 400-500 users (target)",
     ["LinkedIn post #29 — Project 5 growth"]),

    (110, "Tue", 5, "SECOND MOCK INTERVIEW + LeetCode", 2,
     ["**SECOND MOCK INTERVIEW** (Pramp 1 hr)",
      "Note weak areas",
      "1 LeetCode medium"],
     ["pramp.com"], "Mock done + LeetCode",
     ["SECOND MOCK INTERVIEW"]),

    (111, "Wed", 5, "Blog #6 Publish", 2,
     ["'How I Cut LLM Costs 80% Across 4 Production Projects'",
      "Hacker News submission"],
     ["news.ycombinator.com"], "Blog #6 LIVE",
     ["Blog #6 published",
      "LinkedIn post #30 — blog #6"]),

    (112, "Thu", 5, "Phase 5 Retrospective", 2,
     ["4 B2B projects shipped + 1 B2C startup w/ paying users + (maybe) YC submitted",
      "Notion retrospective"],
     [],
     "Phase 5 milestone",
     ["LinkedIn post #31 — phase 5 milestone celebration"]),

    (113, "Sat", 5, "Portfolio Polish — All READMEs", 5,
     ["Architecture diagrams (excalidraw)",
      "Demo GIFs",
      "Tech stack tables",
      "Lessons learned sections — all 5 projects"],
     ["excalidraw.com"], "All 5 READMEs polished", []),

    (114, "Sun", 5, "Sunday Block + Personal Site", 2,
     ["1 hr: Personal site build start (Astro template)",
      "30 min: Reading",
      "30 min: Plan Week 20"],
     ["astro.build/themes"], "Personal site v0", ["Sunday block routine"]),

    (115, "Mon", 5, "Personal Site v1 Deploy", 2,
     ["Astro + Tailwind",
      "Sections: hero, projects, blog, contact",
      "Owned domain",
      "Vercel deploy"],
     [], "Personal site LIVE", []),

    (116, "Tue", 5, "Cross-post Blogs", 2,
     ["All blog posts on personal site",
      "Update Medium/Dev.to bio with site link"],
     [], "Personal site has all 6 blog posts", []),

    (117, "Wed", 5, "YC Decision / Pivot", 2,
     ["IF YC invite: prep Demo Day pitch",
      "IF YC rejected: take learnings into job apps",
      "Either way: Project 5 stays alive"],
     [], None, []),

    # === PHASE 6: Job Hunt + Offer (Days 118-150) ===
    (118, "Thu", 6, "Resume Rewrite", 2,
     ["Single-page",
      "Top: 3-line summary — 'AI Engineer | Fintech | 5 production apps + B2C SaaS w/ paying users'",
      "Projects FIRST",
      "Skills, then .NET background condensed"],
     ["resumeworded.com"], "Resume v1 ready", []),

    (119, "Sat", 6, "Target List + Airtable", 5,
     ["75 companies in spreadsheet:",
      "  30 US fintechs hiring globally remote",
      "  20 GCCs (Goldman, JPMorgan, Visa, Mastercard, Stripe)",
      "  15 Indian fintechs (Razorpay, CRED, Zerodha, INDmoney, Smallcase)",
      "  10 AI-first startups"],
     [], "Target list of 75 ready",
     ["LinkedIn post #32 — 'Starting job search'"]),

    (120, "Sun", 6, "Sunday Block + Admin", 2,
     ["1 hr: TN visa docs gather, OCI check, schedule CA call",
      "30 min: Negotiation prep (Levels.fyi)",
      "30 min: Plan Week 21"],
     ["levels.fyi"], "Visa + tax admin done",
     ["Sunday block routine"]),

    (121, "Mon", 6, "LinkedIn Overhaul", 2,
     ["Banner: AI/fintech themed",
      "Headline: 'AI Engineer | Fintech | YC W26 (if applied) | Production LLM Apps'",
      "About: story-driven w/ Project 5 metrics",
      "Featured: top 4 projects + Project 5",
      "'Open to Work' private mode"],
     [], "LinkedIn polished", []),

    (122, "Tue", 6, "First Wave Apps (25)", 2,
     ["Apply to 25 highest-priority roles",
      "Customize cover letter for top 5",
      "Generic for rest"],
     [], "25 applications sent", []),

    (123, "Wed", 6, "Cold Outreach (15 founders)", 2,
     ["Personalized DMs on LinkedIn + X",
      "Lead with Project 5 metrics"],
     [],
     "15 cold DMs sent",
     ["LinkedIn post #33 — building in public"]),

    (124, "Thu", 6, "Second Wave (25 more)", 2,
     ["25 more applications"],
     [], "50 total applications", []),

    (125, "Sat", 6, "Referrals + Blog #7", 5,
     ["Ping LinkedIn 1st-degree connections at targets (15 messages)",
      "Push Project 5 update to existing users",
      "Blog post #7 — '5 Months In: Lessons from Building AI Fintech'"],
     [], "Blog #7 drafted, 15 referral asks",
     ["Blog #7 draft"]),

    (126, "Sun", 6, "Sunday Block + Interview Prep", 2,
     ["1 hr: LLM system design (3 YouTube vids)",
      "30 min: Reading",
      "30 min: Plan Week 22"],
     [], None, ["Sunday block routine"]),

    (127, "Mon", 6, "LLM System Design Practice", 2,
     ["Design a RAG system",
      "Design an agent system",
      "Practice w/ partner or mock service"],
     [], "System design patterns ready", []),

    (128, "Tue", 6, "Behavioral Prep", 2,
     ["STAR format for top 10 questions",
      "Practice each project pitch in 2 min"],
     [], "Behavioral answers prepped", []),

    (129, "Wed", 6, "THIRD MOCK INTERVIEW + 25 Apps", 2,
     ["**THIRD MOCK INTERVIEW** (Pramp/interviewing.io)",
      "Continue applying — 25 more"],
     [],
     "75 total applications",
     ["THIRD MOCK INTERVIEW"]),

    (130, "Thu", 6, "Coding Practice", 2,
     ["5 LeetCode mediums (Python)",
      "Focus: arrays, strings, hash maps"],
     [], "5 LeetCode done", []),

    (131, "Sat", 6, "Take-home Practice + Blog #7 Publish", 5,
     ["Build a sample take-home in 4 hrs",
      "Public repo for prep",
      "Publish blog #7"],
     [], "Take-home practice done + Blog #7 LIVE",
     ["Blog #7 published"]),

    (132, "Sun", 6, "Sunday Block + Final Blog Outline", 2,
     ["1 hr: Final blog draft — '.NET to AI Engineer in 6 Months'",
      "30 min: Negotiation tactics review",
      "30 min: Plan Week 23"],
     [], "Final blog outlined", ["Sunday block routine"]),

    (133, "Mon", 6, "Live Interview Rounds", 2,
     ["Recruiter screens / coding screens",
      "Track in Airtable"],
     [], "Active interviews in flight", []),

    (134, "Tue", 6, "Live Interview Rounds", 2,
     ["More interview rounds",
      "Coding screens (Python + LLM API)"],
     [], None, []),

    (135, "Wed", 6, "System Design Rounds", 2,
     ["Live system design interviews",
      "Common patterns: design RAG, design agent"],
     [], None, []),

    (136, "Thu", 6, "Behavioral / Final Rounds", 2,
     ["Live behavioral interviews",
      "STAR format"],
     [], None, []),

    (137, "Sat", 6, "Take-home Projects", 5,
     ["Quality > speed",
      "Deploy live, write tests, polish README"],
     [], "Take-homes submitted",
     ["LinkedIn post #34 — interview process insights"]),

    (138, "Sun", 6, "Sunday Block + Offer Compare", 2,
     ["1 hr: Compare offers (if any incoming)",
      "30 min: Negotiation prep",
      "30 min: Plan Week 24"],
     [], None, ["Sunday block routine"]),

    (139, "Mon", 6, "Final Rounds", 2,
     ["Final interviews",
      "Reference checks"],
     [], None, []),

    (140, "Tue", 6, "Final Rounds + LeetCode End", 2,
     ["More finals",
      "Compete offers in flight",
      "**LeetCode cadence ENDS** (~40 problems total)"],
     [], "LeetCode count: ~40", []),

    (141, "Wed", 6, "Final Rounds", 2,
     ["Final interviews continue",
      "Aim: 3 active offers in flight"],
     [], "3 offers target", []),

    (142, "Thu", 6, "Final Rounds Wrap", 2,
     ["Last final-round interviews"],
     [], None, []),

    (143, "Sat", 6, "Negotiate", 5,
     ["Always negotiate (10-25% room)",
      "Use competing offers as leverage",
      "Compare: comp, equity, learning, team, mission, location flexibility"],
     ["levels.fyi"], "Negotiation in progress", []),

    (144, "Sun", 6, "Sunday Block + Decision Matrix", 2,
     ["1 hr: Decision matrix for offers",
      "30 min: Final blog post polish",
      "30 min: Plan Week 25"],
     [], "Decision matrix ready", ["Sunday block routine"]),

    (145, "Mon", 6, "DECISION DAY", 2,
     ["Accept offer (if multiple, pick best fit)",
      "OR: If YC accepted → take YC (different path)",
      "OR: If no offers yet → continue interviewing, extend timeline"],
     [], "Decision made", []),

    (146, "Tue", 6, "Announce + Sign", 2,
     ["Sign offer letter",
      "Plan transition from .NET job"],
     [],
     "Offer signed",
     ["LinkedIn post #35 — 'New role announcement'"]),

    (147, "Wed", 6, "Final Blog Publish", 2,
     ["'.NET to AI Engineer in 6 Months — Full Playbook'",
      "Medium feature submission",
      "Hacker News",
      "LinkedIn carousel"],
     [], "Blog #8 LIVE",
     ["Blog #8 published — final playbook",
      "LinkedIn carousel #36"]),

    (148, "Thu", 6, "Personal Site Update", 2,
     ["Add new role to header",
      "Final polish"],
     [], "Personal site v2", []),

    (149, "Sat", 6, "Knowledge Transfer at .NET Job", 5,
     ["Document handover",
      "Train replacement / colleagues",
      "Maintain professionalism"],
     [], "KT in progress", []),

    (150, "Sun", 6, "🎯 VICTORY", 2,
     ["**Sunday block + reflection:**",
      "Reflect on 6 months",
      "LinkedIn celebration post",
      "Plan first 90 days at new role",
      "Project 5 transition plan (sell? maintain? grow?)",
      "**🎯 TRANSITION COMPLETE**"],
     [],
     "150 days complete. Offer accepted. New chapter begins.",
     ["LinkedIn celebration post — 6-month journey complete",
      "Sunday block routine"]),
]


def render(day):
    num, dow, phase, project, hours, tasks, resources, deliverable, cadences = day
    title = tasks[0].lstrip("*").strip() if tasks else ""
    # Try to extract a short title from project or first task
    short_title = project if project else f"Day {num}"

    md = f"# Day {num:03d} — {short_title}\n\n"
    md += f"**Phase:** {phase} | **Project:** {project} | **Hours:** {hours} | **Day:** {dow}\n\n"
    md += "## Today\n"
    for t in tasks:
        md += f"- {t}\n"
    md += "\n"
    if resources:
        md += "## Resources\n"
        for r in resources:
            md += f"- {r}\n"
        md += "\n"
    if deliverable:
        md += f"## Deliverable\n- {deliverable}\n\n"
    if cadences:
        md += "## Cadences\n"
        for c in cadences:
            md += f"- [ ] {c}\n"
        md += "\n"
    md += "## Done?\n"
    md += "- [ ] All tasks complete\n"
    md += f"- [ ] tracker/days/day-{num:03d}.md filled\n"
    md += "- [ ] Tomorrow's first task pre-decided\n\n"
    md += f"📍 [CURRICULUM.md](../CURRICULUM.md) Day {num}\n"
    return md


count = 0
for day in DAYS:
    num = day[0]
    path = OUT / f"day-{num:03d}.md"
    path.write_text(render(day))
    count += 1
print(f"Generated {count} daily plan files in {OUT}")
